// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Infrastructure.Persistence;

#nullable disable

namespace Warehouse.Infrastructure.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260726163825_FixPurchaseOrderLineKeyTracking")]
    partial class FixPurchaseOrderLineKeyTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Warehouse.Domain.Currencies.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Currencies_Code");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("UX_Currencies_OneDefault")
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("Currencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currencies_Code_NotBlank", "btrim(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_Currencies_Code_Uppercase", "\"Code\" = upper(\"Code\")");

                            t.HasCheckConstraint("CK_Currencies_DecimalPlaces_Valid", "\"DecimalPlaces\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_Currencies_Default_Active", "NOT \"IsDefault\" OR \"IsActive\"");

                            t.HasCheckConstraint("CK_Currencies_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("49f755f8-c6cd-4b22-8615-083b0d5536f2"),
                            Code = "DZD",
                            CreatedAtUtc = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = 2,
                            IsActive = true,
                            IsDefault = true,
                            Name = "Algerian dinar",
                            Symbol = "DA",
                            UpdatedAtUtc = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d3fa10b2-a7fc-4a75-a5f6-1d2a8efc1d96"),
                            Code = "EUR",
                            CreatedAtUtc = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = 2,
                            IsActive = true,
                            IsDefault = false,
                            Name = "Euro",
                            Symbol = "€",
                            UpdatedAtUtc = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6b5c1ad6-f3a3-48e5-8222-4ca8b16a44ce"),
                            Code = "USD",
                            CreatedAtUtc = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = 2,
                            IsActive = true,
                            IsDefault = false,
                            Name = "US dollar",
                            Symbol = "$",
                            UpdatedAtUtc = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Inventory.InventoryAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("InventoryAdjustments", (string)null);
                });

            modelBuilder.Entity("Warehouse.Domain.Inventory.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("InventoryBalances", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryBalances_Quantity_NonNegative", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InventoryAdjustmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("QuantityDeltaInUnit")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryAdjustmentId");

                    b.HasIndex("ProductId", "WarehouseId", "CreatedAtUtc");

                    b.ToTable("InventoryMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryMovements_QuantityDeltaInUnit_NonZero", "\"QuantityDeltaInUnit\" <> 0");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityDelta_NonZero", "\"QuantityDelta\" <> 0");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Sku");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_BaseUnitOfMeasure_Valid", "\"BaseUnitOfMeasure\" IN ('EA', 'KG', 'G', 'L', 'ML', 'M', 'CM', 'MM')");

                            t.HasCheckConstraint("CK_Products_Name_NotBlank", "btrim(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_Products_Sku_NotBlank", "btrim(\"Sku\") <> ''");

                            t.HasCheckConstraint("CK_Products_Sku_Uppercase", "\"Sku\" = upper(\"Sku\")");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Products.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductCategories_Code");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ProductCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductCategories_Code_NotBlank", "btrim(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_ProductCategories_Code_Uppercase", "\"Code\" = upper(\"Code\")");

                            t.HasCheckConstraint("CK_ProductCategories_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Purchasing.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuyerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("DestinationWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWarehouseId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("SupplierId", "Status");

                    b.ToTable("PurchaseOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrders_Status_Valid", "\"Status\" IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Purchasing.PurchaseOrderNumberSequence", b =>
                {
                    b.Property<long>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Value"));

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Value");

                    b.ToTable("PurchaseOrderNumberSequences", (string)null);
                });

            modelBuilder.Entity("Warehouse.Domain.Purchasing.SupplierProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MinimumOrderQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PurchaseUnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierSku")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId", "ProductId", "PurchaseUnitOfMeasure")
                        .IsUnique()
                        .HasDatabaseName("UX_SupplierProducts_Supplier_Product_Unit");

                    b.ToTable("SupplierProducts", null, t =>
                        {
                            t.HasCheckConstraint("CK_SupplierProducts_CurrencyCode_Uppercase", "\"CurrencyCode\" = upper(\"CurrencyCode\")");

                            t.HasCheckConstraint("CK_SupplierProducts_MinimumOrderQuantity_Positive", "\"MinimumOrderQuantity\" > 0");

                            t.HasCheckConstraint("CK_SupplierProducts_UnitPrice_NonNegative", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Suppliers.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Suppliers_Code");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Suppliers_Name");

                    b.ToTable("Suppliers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Suppliers_Code_NotBlank", "btrim(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_Suppliers_Code_Uppercase", "\"Code\" = upper(\"Code\")");

                            t.HasCheckConstraint("CK_Suppliers_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Warehouses_Code");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Warehouses_Name");

                    b.ToTable("Warehouses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Warehouses_Code_NotBlank", "btrim(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_Warehouses_Code_Uppercase", "\"Code\" = upper(\"Code\")");

                            t.HasCheckConstraint("CK_Warehouses_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("Warehouse.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Warehouse.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Warehouse.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Warehouse.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Warehouse.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("Warehouse.Domain.Inventory.InventoryAdjustment", null)
                        .WithMany()
                        .HasForeignKey("InventoryAdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Warehouse.Domain.Products.Product", b =>
                {
                    b.HasOne("Warehouse.Domain.Products.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Warehouse.Domain.Products.ProductMeasurements", "Measurements", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DimensionUnitOfMeasure")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<decimal?>("GrossWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)");

                            b1.Property<decimal?>("Height")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)");

                            b1.Property<decimal?>("Length")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)");

                            b1.Property<decimal?>("NetWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)");

                            b1.Property<string>("WeightUnitOfMeasure")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<decimal?>("Width")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("Warehouse.Domain.Products.ProductUnitConversion", "UnitConversions", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitOfMeasure")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<bool>("AllowsFractionalQuantity")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false);

                            b1.Property<decimal>("QuantityInBaseUnit")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)");

                            b1.HasKey("ProductId", "UnitOfMeasure");

                            b1.ToTable("ProductUnitConversions", null, t =>
                                {
                                    t.HasCheckConstraint("CK_ProductUnitConversions_QuantityInBaseUnit_Positive", "\"QuantityInBaseUnit\" > 0");

                                    t.HasCheckConstraint("CK_ProductUnitConversions_UnitOfMeasure_NotBlank", "btrim(\"UnitOfMeasure\") <> ''");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Measurements");

                    b.Navigation("UnitConversions");
                });

            modelBuilder.Entity("Warehouse.Domain.Products.ProductCategory", b =>
                {
                    b.HasOne("Warehouse.Domain.Products.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Warehouse.Domain.Purchasing.PurchaseOrder", b =>
                {
                    b.HasOne("Warehouse.Domain.Warehouses.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Warehouse.Domain.Suppliers.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Warehouse.Domain.Purchasing.PurchaseOrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("ConversionFactorToBaseUnit")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<decimal>("LineAmount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("integer");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("ProductSku")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<Guid>("PurchaseOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PurchaseUnitOfMeasure")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)");

                            b1.Property<decimal>("QuantityInBaseUnit")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)");

                            b1.Property<Guid>("SupplierProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SupplierSku")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.HasIndex("PurchaseOrderId", "LineNumber")
                                .IsUnique();

                            b1.HasIndex("SupplierProductId", "PurchaseUnitOfMeasure");

                            b1.ToTable("PurchaseOrderLines", null, t =>
                                {
                                    t.HasCheckConstraint("CK_PurchaseOrderLines_CurrencyCode_Uppercase", "\"CurrencyCode\" = upper(\"CurrencyCode\")");

                                    t.HasCheckConstraint("CK_PurchaseOrderLines_Quantity_Positive", "\"Quantity\" > 0");

                                    t.HasCheckConstraint("CK_PurchaseOrderLines_UnitPrice_NonNegative", "\"UnitPrice\" >= 0");
                                });

                            b1.HasOne("Warehouse.Domain.Products.Product", null)
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");

                            b1.HasOne("Warehouse.Domain.Purchasing.SupplierProduct", null)
                                .WithMany()
                                .HasForeignKey("SupplierProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsMany("Warehouse.Domain.Purchasing.PurchaseOrderStatusHistory", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ActorUserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ChangedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("PreviousStatus")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PurchaseOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PurchaseOrderId");

                            b1.ToTable("PurchaseOrderStatusHistory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("Lines");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Warehouse.Domain.Purchasing.SupplierProduct", b =>
                {
                    b.HasOne("Warehouse.Domain.Currencies.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Warehouse.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Warehouse.Domain.Suppliers.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("Warehouse.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Warehouse.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
