import { Button, Form, Input, Modal, Select, Table, Typography } from "antd";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useCreateProductCategory, useProductCategories, useUpdateProductCategory } from "../api/useProductCategories";
import type { ProductCategory } from "../api/productTypes";

type Values = Pick<ProductCategory, "code" | "name" | "parentCategoryId">;
export function ProductCategoryListPage() { const { t } = useTranslation(); const [editing, setEditing] = useState<ProductCategory | undefined>(); const categories = useProductCategories(); const create = useCreateProductCategory(); const update = useUpdateProductCategory(); async function submit(values: Values) { if (editing) await update.mutateAsync({ id: editing.id, input: values }); else await create.mutateAsync(values); setEditing(undefined); }
  return <section><div className="page-heading"><div><Typography.Title level={2}>{t("masterData.categories.title")}</Typography.Title><Typography.Paragraph type="secondary">{t("masterData.categories.subtitle")}</Typography.Paragraph></div><Button type="primary" onClick={() => setEditing({} as ProductCategory)}>{t("masterData.new")}</Button></div><Table rowKey="id" loading={categories.isLoading} dataSource={categories.data?.items} pagination={false} columns={[{ title: t("masterData.code"), dataIndex: "code" }, { title: t("masterData.name"), dataIndex: "name" }, { title: t("masterData.actions"), render: (_, category) => <Button type="link" onClick={() => setEditing(category)}>{t("masterData.edit")}</Button> }]} /><Modal open={editing !== undefined} footer={null} title={editing?.id ? t("masterData.categories.edit") : t("masterData.categories.new")} onCancel={() => setEditing(undefined)}><CategoryForm initial={editing?.id ? editing : undefined} categories={categories.data?.items ?? []} onSubmit={submit} loading={create.isPending || update.isPending} /></Modal></section>; }
function CategoryForm({ initial, categories, onSubmit, loading }: { initial?: ProductCategory; categories: ProductCategory[]; onSubmit: (values: Values) => Promise<void>; loading: boolean }) { const { t } = useTranslation(); return <Form layout="vertical" initialValues={initial} onFinish={onSubmit}><Form.Item label={t("masterData.code")} name="code" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label={t("masterData.name")} name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label={t("masterData.categories.parent")} name="parentCategoryId"><Select allowClear options={categories.filter(c => c.id !== initial?.id).map(c => ({ value: c.id, label: `${c.code} — ${c.name}` }))} /></Form.Item><Button htmlType="submit" loading={loading} type="primary">{t("masterData.save")}</Button></Form>; }
